---
- name: Download and Extract oracle jdk archive to {{ java_oracle_jdk_directory }}
  ansible.builtin.unarchive:
    src: "{{ java_oracle_jdk_url }}"
    dest: "{{ java_oracle_jdk_directory }}"
    creates: "{{ java_oracle_jdk_directory }}/jdk{{ java_oracle_jdk_version }}"
    remote_src: true
