---

- name: Install OracleJDK {{ java_oracle_jdk_version }}
  block:
    - name: Download and Install OracleJDK to {{ java_oracle_jdk_directory }}
      ansible.builtin.unarchive:
        src: "{{ java_oracle_jdk_url }}"
        dest: "{{ java_oracle_jdk_directory }}"
        creates: "{{ java_oracle_jdk_directory }}/jdk{{ java_oracle_jdk_version }}"
        remote_src: true
        validate_certs: false
  rescue:
    - name: Register if OracleJDK package exists locally
      ansible.builtin.stat:
        path: "{{ java_oracle_jdk_package_local_path }}"
      register: result
      delegate_to: localhost
      run_once: true

    - name: Echo message and fail a task if file not exists
      ansible.builtin.fail:
        msg: "You have to put a package locally and set environment java_oracle_jdk_package_local_path"
      when: not result.stat.exists

    - name: "Extract archive to {{ java_oracle_jdk_directory }}"
      ansible.builtin.unarchive:
        src: "{{ java_oracle_jdk_package_local_path }}"
        dest: /opt
        creates: "{{ java_oracle_jdk_directory }}/jdk{{ java_oracle_jdk_version }}"
      when: result.stat.exists
