---
- name: Include OS-specific variables for Fedora or FreeBSD
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'FreeBSD' or ansible_distribution == 'Fedora'

- name: Include version-specific variables for CentOS/RHEL
  ansible.builtin.include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == 'CentOS' or
        ansible_distribution == 'Red Hat Enterprise Linux' or
        ansible_distribution == 'RedHat'

- name: Include version-specific variables for Ubuntu
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == 'Ubuntu'

- name: Include version-specific variables for Debian
  ansible.builtin.include_vars: "{{ ansible_distribution | title }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'

- name: Define java_packages
  ansible.builtin.set_fact:
    java_packages: "{{ __java_packages | list }}"
  when: java_packages is not defined

# Setup/install tasks.
- name: Install OpenJdk
  block:
    - name: Install OpenJdk RedHat
      ansible.builtin.include_tasks: install-OpenJdk-RedHat.yml
      when:
        - ansible_os_family == 'RedHat'

    - name: Install OpenJdk Debian
      ansible.builtin.include_tasks: install-OpenJdk-Debian.yml
      when:
        - ansible_os_family == 'Debian'

    - name: Install OpenJdk FreeBSD
      ansible.builtin.include_tasks: install-OpenJdk-FreeBSD.yml
      when:
        - ansible_os_family == 'FreeBSD'
  when: not java_oracle_jdk_install

- name: Install OracleJDK
  ansible.builtin.include_tasks: install-OracleJdk.yml
  when: java_oracle_jdk_install

# Environment setup.
- name: Set JAVA_HOME if configured
  ansible.builtin.template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined and java_home
