---

name: Generate Release
'on':
  pull_request:
    branches:
      - master
    types:
      - closed
  push:
    branches:
      - master

jobs:
  generate_release:
    name: Release
    # if: contains(github.event.pull_request.head.ref, 'release/') && github.event.pull_request.merged == true
    if: contains(github.event.pull_request.head.ref, 'release/') && github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch version
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            # VERSION=$(git describe --abbrev=0 --tags)
            echo "test if"
          else
            VERSION=$(echo "${GITHUB_HEAD_REF}" | sed "s/release\\///")
          fi
          echo "${VERSION}" 
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
        id: fetch-version

      - name: Generate release notes
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          tag_name: ${{ steps.fetch-version.outputs.version }}
          generate_release_notes: true
