---
name: Generate Release

on:
  # pull_request:
  #   branches:
  #     - master
  #   types:
  #     - closed
  # push:
  #   branches:
  #     - master
  workflow_run:
    workflows: ["CI"]
    types: 
      - completed
    pull_request:
      branches:
        - master
      types:
        - closed
    push:
      branches:
        - master


jobs:
  generate_release:
    name: Release
    # if: contains(github.event.pull_request.head.ref, 'release/') && github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch version
        run: |
          echo "${{ github.event_name }}"
          if [ "${{ github.event_name }}" == "push" ]; then
            LATEST_TAG=$(curl -s "https://api.github.com/repos/sukhorukovmv/ansible-role-java/tags" | jq -r '.[0].name')
            MAJOR=$(echo ${LATEST_TAG} | cut -d'.' -f1)
            MINOR=$(echo ${LATEST_TAG} | cut -d'.' -f2)
            PATCH=$(echo ${LATEST_TAG} | cut -d'.' -f3)
            NEW_PATCH=$((PATCH + 1))
            VERSION=$(printf "%d.%d.%d" $MAJOR $MINOR $NEW_PATCH)
          else
            VERSION=$(echo "${GITHUB_HEAD_REF}" | sed "s/release\\///")
          fi
          echo "${VERSION}" 
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
        id: fetch-version
      
      - name: Generate release notes
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          tag_name: ${{ steps.fetch-version.outputs.version }}
          generate_release_notes: true
